# Auto update from Guizhan Build is enabled by default.
auto-update: true

guide:
  survival-improvements: true
  cheat-improvements: true

improvements:
  pinyin-search: true
  bookmark: true

# Do not change this value unless you know what you are doing.
config-version: 1.0

# Do not change this value unless you know what you are doing.
debug: false
