name: JustEnoughGuide
author: balugaq
description: This is a Slimefun addon and improved the guide's search module.
main: com.balugaq.jeg.JustEnoughGuide
website: https://github.com/balugaq/JustEnoughGuide
version: ${project.version}
api-version: 1.17
depend:
  - Slimefun
softdepend:
  - GuizhanLibPlugin
